/**
 * Seed script: crea una presentación de 14 slides por cada nicho.
 * Ejecutar: npx tsx scripts/seed-presentations.ts
 */
import { prisma } from "../lib/db";

const PLANS = [
	{
		name: "Wallet",
		price: "$19",
		period: "mes",
		highlight: false,
		features: ["Tarjetas Apple & Google Wallet", "Hasta 300 transacciones/mes", "Notificaciones por geolocalización", "Analytics con KPIs y RFM", "Soporte prioritario"],
	},
	{
		name: "Shared",
		price: "$29",
		period: "mes",
		highlight: false,
		features: ["Apple & Google Wallet incluidos", "App marketplace compartida", "Hasta 600 transacciones/mes", "Dashboard completo KPIs y RFM", "Multi-sucursal"],
	},
	{
		name: "Branded",
		price: "$99",
		period: "mes",
		highlight: true,
		features: ["Apple & Google Wallet incluidos", "Tu propia app marca blanca", "Hasta 2,000 transacciones/mes", "Dashboard completo KPIs y RFM", "Notificaciones WhatsApp Business"],
	},
	{
		name: "Premium",
		price: "$299",
		period: "mes",
		highlight: false,
		features: ["Apple & Google Wallet incluidos", "App totalmente personalizada", "Hasta 6,000 transacciones/mes", "REST API y webhooks", "Soporte y onboarding prioritarios"],
	},
];

const CTA_CONTACT = {
	whatsapp: "+52 55 0000 0000",
	email: "hola@xtarly.com",
	web: "xtarly.com",
};

const VS_PAPER = { headline: "Las tarjetas de papel ya no funcionan.", subheadline: "Compara lo que tienes hoy con lo que puede tener tu negocio.", variant: "paper" as const };

// ─── CONTENIDO POR NICHO ─────────────────────────────────────────────────────

type Slides = { type: string; order: number; content: Record<string, unknown> }[];

function cafeterias(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Que tu café de las mañanas tenga nombre, apellido y 10 sellos ganados.", subheadline: "Convierte la rutina de tus clientes en lealtad medible y recompensada.", tagline: "Xtarly Rewards — Cafeterías" } },
		{ type: "problem", order: 2, content: { title: "El problema real de las cafeterías", points: [{ emoji: "👻", text: "El 70% de tus clientes son desconocidos. Llegan, pagan y se van — sin nombre, sin historial, sin manera de recuperarlos." }, { emoji: "💸", text: "Un cliente de rutina vale $1,800–$5,400 al año. Si se va a la cafetería de enfrente, lo pierdes para siempre." }, { emoji: "📉", text: "Starbucks retiene al 55% de sus ventas con su programa de loyalty. Tú no tienes nada con qué competir." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: fideliza a tus clientes habituales", description: "Convierte cada visita de la mañana en un sello más cerca del café gratis. Tú conoces a tus clientes, los retienes y los haces regresar.", benefitPoints: ["Programa de sellos automático — sin tarjetas físicas", "Wallet digital en cada iPhone y Android de tu cliente", "Push cuando se acercan, cuando casi completan y en su cumpleaños"] } },
		{ type: "how-it-works", order: 4, content: { headline: "Tu cajero no necesita aprender nada nuevo.", subheadline: "Sin hardware extra. El cajero usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet y muestra su código al cajero." }, { number: 2, icon: "📷", title: "El cajero escanea y registra", description: "Xtarly Cashier en iOS o Android. Ingresa el consumo y confirma en 5 segundos." }, { number: 3, icon: "⭐", title: "Sello sumado al instante", description: "Push al cliente. Su Wallet se actualiza automáticamente." }] } },
		{ type: "wallet", order: 5, content: { headline: "Vive en el bolsillo de tu cliente. Cada mañana.", subheadline: "La tarjeta aparece en su lock screen cuando pasa frente a tu cafetería. Sin abrir ninguna app.", benefits: ["Nunca se olvida en casa — vive en Apple y Google Wallet", "Notificación de proximidad al pasar enfrente a las 7am", "Se actualiza en cada visita sin que el cliente haga nada", "Se agrega en 10 segundos la primera vez"], stat: "El diferenciador que las tarjetas de papel nunca podrán ofrecer.", notificationText: "Estás cerca de tu cafetería favorita ☕ — tienes 8 sellos, ¡solo falta 1!" } },
		{ type: "journey", order: 6, content: { headline: "La experiencia que tus clientes van a amar.", subheadline: "De cliente anónimo a fan fiel — en 5 momentos.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Escanea el QR en caja y agrega la tarjeta a Wallet en 10 segundos." }, { number: 2, icon: "☕", title: "Acumula sellos", description: "Cada café suma 1 sello. Ve su progreso en tiempo real: 3/10, 7/10..." }, { number: 3, icon: "🔔", title: "Recibe notificaciones", description: "\"Ya tienes 9 sellos — ¡tu café gratis está a uno de distancia!\"" }, { number: 4, icon: "🎁", title: "Canjea su café gratis", description: "Muestra el QR en caja. El cajero confirma en 3 segundos." }, { number: 5, icon: "💛", title: "Regresa más seguido", description: "Tu cafetería ya no es una opción más — es su rutina con beneficios." }] } },
		{ type: "analytics", order: 7, content: { headline: "Por primera vez, conoces a tus clientes.", subheadline: "Cuántos vienen, qué tan seguido, cuánto gastan. Todo en tiempo real.", kpis: [{ label: "Clientes activos", value: "284", delta: "+22 este mes", positive: true }, { label: "Membership rate", value: "38%", delta: "+5% vs mes anterior", positive: true }, { label: "Member lift", value: "+31%", delta: "visitas extra vs no-miembros", positive: true }, { label: "Ticket promedio", value: "$94", delta: "+$18 con loyalty", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "Habla con tus clientes cuando más importa.", subheadline: "Push directo a su teléfono. Sin algoritmo. Sin costo adicional.", notifications: [{ type: "proximity", title: "Xtarly Rewards", body: "Buenos días ☕ — pasas cerca de tu cafetería favorita. Tienes 8 sellos, ¡hoy completas!", time: "7:14 AM" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Feliz cumpleaños, Ana! Hoy tu café va por nuestra cuenta. Te esperamos.", time: "8:00 AM" }, { type: "winback", title: "Xtarly Rewards", body: "Hace 10 días que no te vemos ☕ Tu macchiato favorito te extraña. ¿Volvemos a la rutina?", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "Lunes de sellos dobles ⭐⭐ — solo hoy de 7 a 10am. ¡No faltes!", time: "lun 6:45" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "El programa que se paga a sí mismo.", subheadline: "Ejemplo real para una cafetería de 80 visitas al día:", dailyVisits: 80, avgTicket: 90, enrollmentRate: 35, frequencyLift: 30, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "☕", title: "Sellos digitales", description: "10 cafés = 1 café gratis. Configurable por tipo de bebida o monto." }, { emoji: "💳", title: "Apple & Google Wallet", description: "La tarjeta de tu cafetería vive en el teléfono del cliente." }, { emoji: "📊", title: "Dashboard en tiempo real", description: "Cuántos clientes, con qué frecuencia, cuánto gastan. RFM completo." }, { emoji: "🔔", title: "Push automáticos", description: "Winback, cumpleaños, proximidad, campañas de doble sellos." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Antes no sabía quiénes eran mis clientes de todos los días. Ahora tengo 340 registrados, sé cuáles son mis mejores y cuáles llevan tiempo sin venir. En 2 meses subí las visitas un 28%.", author: "Patricia Mendoza", business: "Café La Viga, Condesa CDMX" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "14 días gratis. Sin compromisos.", subtitle: "Tu programa de recompensas para cafetería listo en 5 minutos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function restaurantes(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Que la reservación sea tuya. Y el cliente también.", subheadline: "Deja de pagar 28% a Uber Eats por clientes que ya son tuyos.", tagline: "Xtarly Rewards — Restaurantes" } },
		{ type: "problem", order: 2, content: { title: "El problema real de los restaurantes", points: [{ emoji: "📦", text: "Las plataformas de delivery cobran 25-30% de comisión y se quedan con los datos de tus clientes. Tú pierdes la relación." }, { emoji: "👻", text: "El 80% de tus comensales son anónimos. No tienes cómo contactarlos para traerlos de regreso." }, { emoji: "📉", text: "Un comensal frecuente vale $3,000-$9,000 al año. Sin loyalty, no hay razón para que te elijan a ti en lugar de la competencia." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: tus clientes son tuyos, no de Uber", description: "Registra a cada comensal, acumula sus visitas, recompénsalos directamente — sin intermediarios y sin comisiones.", benefitPoints: ["Puntos por cada visita o monto consumido — configurable", "Wallet digital con nivel VIP visible en su teléfono", "Campañas de reactivación para días lentos como martes"] } },
		{ type: "how-it-works", order: 4, content: { headline: "El mesero registra en 5 segundos. Eso es todo.", subheadline: "Sin hardware extra. El mesero usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El comensal muestra su QR", description: "Abre su app o Wallet y muestra su código al mesero." }, { number: 2, icon: "📷", title: "El mesero escanea y registra", description: "Xtarly Cashier en iOS o Android. Ingresa el consumo y confirma en 5 segundos." }, { number: 3, icon: "⭐", title: "Puntos sumados al instante", description: "Push al comensal. Wallet actualizado con su nuevo nivel VIP." }] } },
		{ type: "wallet", order: 5, content: { headline: "Tu restaurante siempre presente en su teléfono.", subheadline: "La tarjeta aparece cuando el cliente está cerca. Sin que abra ninguna app.", benefits: ["Nivel VIP visible — Bronze, Silver, Gold, Platinum", "Notificación automática al pasar frente al restaurante", "Puntos y nivel actualizados en cada visita", "Canje de recompensas con QR en 3 segundos"], stat: "Los clientes con nivel VIP visitan 2.3x más que los clientes sin programa.", notificationText: "Estás cerca de tu restaurante favorito 🍽️ — tienes 340 puntos. ¿Hoy comemos?" } },
		{ type: "journey", order: 6, content: { headline: "De comensal ocasional a cliente VIP.", subheadline: "El viaje completo en 5 momentos.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Escanea el QR de la cuenta y agrega la tarjeta a Wallet." }, { number: 2, icon: "⭐", title: "Acumula puntos", description: "$1 gastado = 1 punto. En cada visita ve su saldo crecer." }, { number: 3, icon: "🥂", title: "Sube de nivel", description: "Silver: postre gratis. Gold: mesa sin espera. Platinum: acceso especial." }, { number: 4, icon: "🎁", title: "Canjea su recompensa", description: "Descuento en cuenta, postre gratis o botella de vino por cumpleaños." }, { number: 5, icon: "💛", title: "Tu restaurante es su favorito", description: "Ya no elige por precio — elige porque lo conoces y lo recompensas." }] } },
		{ type: "analytics", order: 7, content: { headline: "Conoce a tus mejores 50 comensales.", subheadline: "Y a los 30 que están a punto de irse.", kpis: [{ label: "Comensales activos", value: "512", delta: "+41 este mes", positive: true }, { label: "Membership rate", value: "29%", delta: "+3% vs mes anterior", positive: true }, { label: "Frecuencia mensual", value: "1.8x", delta: "+0.4x con loyalty", positive: true }, { label: "Ticket promedio", value: "$342", delta: "+$67 con loyalty", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "Llena tu restaurante los días lentos.", subheadline: "Push segmentados para los momentos que más importan.", notifications: [{ type: "campaign", title: "Xtarly Rewards", body: "🍽️ Martes de puntos dobles — reserva tu mesa y gana el doble. Solo hoy.", time: "lun 7pm" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Feliz cumpleaños! Este mes tu postre favorito va por cuenta de la casa.", time: "8:00 AM" }, { type: "winback", title: "Xtarly Rewards", body: "Hace 30 días que no te vemos 🍷 — tu mesa favorita te espera este viernes.", time: "jue 12pm" }, { type: "proximity", title: "Xtarly Rewards", body: "Pasas cerca 🍽️ — tienes 450 puntos. ¡Hoy alcanzas tu postre gratis!", time: "2:15 PM" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "Más rentable que cualquier campaña en Instagram.", subheadline: "Ejemplo real para un restaurante de 120 comidas al día:", dailyVisits: 120, avgTicket: 320, enrollmentRate: 30, frequencyLift: 25, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "🍽️", title: "Puntos y niveles VIP", description: "Bronze → Silver → Gold → Platinum. Cada nivel desbloquea beneficios exclusivos." }, { emoji: "💳", title: "Apple & Google Wallet", description: "Tarjeta con nivel VIP siempre visible en el teléfono del comensal." }, { emoji: "📊", title: "Segmentos RFM", description: "Identifica Champions, clientes en riesgo y los que casi se van." }, { emoji: "🔔", title: "Campañas para días lentos", description: "Puntos dobles en martes, ofertas de temporada, cumpleaños VIP." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Antes pagaba $4,000 al mes en anuncios de Instagram para llenar las mesas del martes. Ahora mando un push a mis 200 clientes Gold y el martes se llena solo. Ahorré el presupuesto de marketing completo.", author: "Roberto Gutiérrez", business: "Restaurante El Refugio, Polanco CDMX" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "Deja de pagar comisiones por tus propios clientes.", subtitle: "Tu programa de lealtad listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function pastelerias(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Cada pieza cuenta. Cada cliente también.", subheadline: "Convierte a tus compradores de temporada en clientes de todo el año.", tagline: "Xtarly Rewards — Pastelerías" } },
		{ type: "problem", order: 2, content: { title: "El problema real de las pastelerías", points: [{ emoji: "📅", text: "El 60% de tus ventas se concentra en 4 temporadas al año. Los demás meses, los clientes simplemente no vuelven sin un incentivo." }, { emoji: "👻", text: "Cuando el cliente hace un pedido especial, no tienes forma de contactarlo para el siguiente cumpleaños o temporada." }, { emoji: "🎂", text: "Sin un programa de lealtad, cada pedido de pastel es una transacción única — nunca una relación." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: convierte temporadas en fidelidad todo el año", description: "Acumula sellos en cada visita semanal y puntos en pedidos especiales. Tus clientes vuelven para temporadas, aniversarios y sin razón especial.", benefitPoints: ["Sellos para la rutina semanal — pieza + café", "Puntos en pedidos especiales — pasteles de boda, quinceañeras", "Acceso anticipado a colecciones de temporada para miembros VIP"] } },
		{ type: "how-it-works", order: 4, content: { headline: "Tan simple como pedir un pastel.", subheadline: "Sin hardware extra. El cajero usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet y muestra su código al cajero." }, { number: 2, icon: "📷", title: "El cajero escanea y registra", description: "Xtarly Cashier en iOS o Android. Confirma sellos o puntos en 5 segundos." }, { number: 3, icon: "⭐", title: "Sello o puntos al instante", description: "Push al cliente. Su progreso actualizado en Wallet." }] } },
		{ type: "wallet", order: 5, content: { headline: "Tu pastelería siempre presente — no solo en temporada.", subheadline: "La tarjeta de loyalty aparece cuando el cliente pasa frente a tu local.", benefits: ["Recordatorio de temporada automático — \"¡Ya llegó Navidad!\"", "Notificación de proximidad para impulsar visitas espontáneas", "Puntos y sellos visibles en todo momento", "Acceso VIP a colecciones limitadas desde la tarjeta"], stat: "Los clientes con loyalty compran 2.1x más piezas de temporada que los anónimos.", notificationText: "🎂 Ya llegó la colección navideña — miembros VIP tienen acceso desde hoy. ¡Te esperamos!" } },
		{ type: "journey", order: 6, content: { headline: "De compra ocasional a cliente fiel todo el año.", subheadline: "5 momentos que cambian la relación.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Agrega la tarjeta a Wallet al pagar su primera pieza." }, { number: 2, icon: "🍰", title: "Acumula sellos", description: "Cada visita semanal suma 1 sello. 10 visitas = pieza gratis." }, { number: 3, icon: "🎄", title: "Acceso anticipado VIP", description: "\"Miembros Silver en adelante acceden al catálogo navideño desde hoy.\"" }, { number: 4, icon: "🎁", title: "Canjea su recompensa", description: "Pieza gratis, descuento en pastel de cumpleaños o diseño personalizado." }, { number: 5, icon: "💛", title: "Vuelve todo el año", description: "Ya no solo en temporada — hay razones para venir cada semana." }] } },
		{ type: "analytics", order: 7, content: { headline: "Sabe qué cliente viene cada semana y cuál solo en Navidad.", subheadline: "RFM para pastelerías: frecuencia + temporada + monto.", kpis: [{ label: "Clientes activos", value: "198", delta: "+17 este mes", positive: true }, { label: "Membership rate", value: "42%", delta: "+6% vs mes anterior", positive: true }, { label: "Frecuencia inter-temporada", value: "+38%", delta: "vs clientes sin programa", positive: true }, { label: "Ticket promedio", value: "$187", delta: "+$44 con loyalty", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "Activa ventas en cualquier momento del año.", subheadline: "No esperes a que llegue la temporada — créala.", notifications: [{ type: "campaign", title: "Xtarly Rewards", body: "🎄 Colección navideña disponible — miembros VIP tienen 48h de ventaja. ¡Aparta tu pastel!", time: "nov 15" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 El cumpleaños de alguien especial se acerca — 15% de descuento en tu próximo pastel.", time: "8:00 AM" }, { type: "winback", title: "Xtarly Rewards", body: "Hace 3 semanas que no nos visitas 🍰 — tu pieza favorita sigue aquí. Puntos dobles hoy.", time: "viernes" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Tus sellos vencen en 5 días — ¡ya casi tienes tu pieza gratis!", time: "ayer" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "La pastelería que fideliza vende más los 12 meses.", subheadline: "Ejemplo real para una pastelería de 45 visitas al día:", dailyVisits: 45, avgTicket: 180, enrollmentRate: 40, frequencyLift: 30, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "🍰", title: "Sellos + puntos combinados", description: "Sellos para la rutina semanal, puntos para pedidos especiales grandes." }, { emoji: "💳", title: "Apple & Google Wallet", description: "Tarjeta con nivel VIP y acceso anticipado a colecciones." }, { emoji: "📊", title: "Segmentos por temporada", description: "Identifica quién solo compra en Navidad y actívalos con tiempo." }, { emoji: "🔔", title: "Campañas de temporada automáticas", description: "Push pre-temporada, cumpleaños y recordatorios de puntos por vencer." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Siempre dependía de diciembre y Día de Muertos. Ahora mis clientes vienen cada viernes por su sello semanal. Julio, que antes era muerto, este año subió 35% gracias a las campañas de cumpleaños.", author: "Sofía Ramírez", business: "Pastelería La Dulce Vida, San Pedro Garza García" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "Tu pastelería merece clientes todo el año.", subtitle: "Programa de lealtad listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function autolavados(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Cada lavado cuenta. Tu próximo lavado gratis está más cerca.", subheadline: "El programa de lealtad es el único diferenciador real entre autolavados.", tagline: "Xtarly Rewards — Autolavados" } },
		{ type: "problem", order: 2, content: { title: "El problema real de los autolavados", points: [{ emoji: "🔄", text: "El servicio es casi idéntico en todos los autolavados de la zona. El cliente elige por precio o conveniencia — no por lealtad." }, { emoji: "👻", text: "No tienes datos de tus clientes. Si abren uno nuevo a 3 cuadras, no puedes hacer nada para retenerlos." }, { emoji: "💸", text: "Un cliente frecuente lava 2-4 veces al mes × $150-$400 = $3,600-$19,200 al año. Perderlo duele." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: convierte el hábito en lealtad", description: "Con sellos digitales, cada lavado lo acerca a uno gratis. El cliente tiene una razón económica para volver siempre al mismo autolavado.", benefitPoints: ["5 lavados = 1 lavado gratis — simple y motivador", "Wallet digital — nunca olvidan la tarjeta en casa", "Push de reactivación cuando llevan días sin venir"] } },
		{ type: "how-it-works", order: 4, content: { headline: "El operador registra en 5 segundos. Eso es todo.", subheadline: "Sin hardware extra. El operador usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet y muestra su código al operador." }, { number: 2, icon: "📷", title: "El operador escanea y registra", description: "Xtarly Cashier en iOS o Android. Confirma el sello en 5 segundos." }, { number: 3, icon: "⭐", title: "Sello sumado al instante", description: "Push al cliente. 5 sellos = lavado gratis. Progreso visible en Wallet." }] } },
		{ type: "wallet", order: 5, content: { headline: "Recuérdales que tienen sellos acumulados.", subheadline: "La notificación aparece cuando el cliente pasa frente a tu autolavado.", benefits: ["Nunca olvida cuántos sellos tiene acumulados", "Notificación de proximidad — \"Pasas cerca, tienes 4 sellos\"", "Actualización automática después de cada lavado", "Canje del lavado gratis con QR en 5 segundos"], stat: "Los clientes con programa de sellos visitan 40% más frecuente que los que no tienen.", notificationText: "🚗 Pasas por aquí — tienes 4 de 5 sellos. ¡Un lavado más y el próximo va gratis!" } },
		{ type: "journey", order: 6, content: { headline: "De cliente que llega por accidente a cliente que vuelve por hábito.", subheadline: "El ciclo de retención de un autolavado.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Escanea el QR y agrega la tarjeta a Wallet mientras lavan su auto." }, { number: 2, icon: "🚗", title: "Acumula sellos", description: "Cada lavado = 1 sello. Ve el progreso: 1/5, 3/5, 4/5..." }, { number: 3, icon: "🔔", title: "Notificación de proximidad", description: "\"Pasas por aquí y tienes 4 sellos — ¡hoy completas!\"" }, { number: 4, icon: "🎁", title: "Lavado gratis", description: "Al 5to sello, muestra el QR y el lavado va por cuenta de la casa." }, { number: 5, icon: "💛", title: "El hábito está formado", description: "Ya no lava en cualquier lugar — lava donde tiene sus sellos." }] } },
		{ type: "analytics", order: 7, content: { headline: "Sabe exactamente cuántos clientes tienes y con qué frecuencia vienen.", subheadline: "Identifica quién está a punto de irse antes de que pase.", kpis: [{ label: "Clientes activos", value: "347", delta: "+28 este mes", positive: true }, { label: "Membership rate", value: "44%", delta: "+7% vs mes anterior", positive: true }, { label: "Frecuencia mensual", value: "2.8x", delta: "+0.7x con loyalty", positive: true }, { label: "Retención mensual", value: "71%", delta: "+18% vs sin programa", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "Activa visitas cuando el clima lo pide.", subheadline: "Campañas manuales para días estratégicos.", notifications: [{ type: "campaign", title: "Xtarly Rewards", body: "🌧️ Lluvia en CDMX hoy — mañana lunes: sellos dobles en todos los servicios.", time: "dom 8pm" }, { type: "proximity", title: "Xtarly Rewards", body: "🚗 Pasas por aquí y tienes 4 de 5 sellos. ¡Hoy tu lavado gratis está a uno!", time: "ahora" }, { type: "winback", title: "Xtarly Rewards", body: "Hace 18 días que no lavas tu auto 🚿 — tus sellos te esperan. ¿Hoy?", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "🏖️ Prepara tu auto para el puente — jueves y viernes sellos dobles.", time: "mié 12pm" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "El programa que se paga con el primer mes.", subheadline: "Ejemplo real para un autolavado de 90 vehículos al día:", dailyVisits: 90, avgTicket: 200, enrollmentRate: 40, frequencyLift: 35, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "🚗", title: "Sellos digitales 5×1", description: "Configurable: 5, 8 o 10 lavados = 1 gratis. Ajustado a tu margen." }, { emoji: "💳", title: "Apple & Google Wallet", description: "El cliente siempre sabe cuántos sellos tiene — en su teléfono." }, { emoji: "📊", title: "Retención en tiempo real", description: "% de clientes que volvieron este mes vs el anterior." }, { emoji: "🔔", title: "Campañas climáticas", description: "Push manuales en días de lluvia, puentes y temporadas altas." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Abrieron un autolavado nuevo a 2 cuadras y pensé que iba a perder la mitad de mis clientes. Con Xtarly, los que tienen sellos acumulados no se van — tienen razón para quedarse conmigo.", author: "Miguel Hernández", business: "Auto Spa Express, Monterrey NL" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "La competencia no tiene esto. Tú sí puedes.", subtitle: "Programa de sellos listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function spas(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Cada momento de paz merece su recompensa.", subheadline: "Convierte a tus clientes de autocuidado en miembros VIP que nunca se van.", tagline: "Xtarly Rewards — Spas & Wellness" } },
		{ type: "problem", order: 2, content: { title: "El problema real de los spas y wellness", points: [{ emoji: "💆‍♀️", text: "Tu cliente más valioso viene 1-2 veces al mes y gasta $600-$2,000. Sin un programa, no hay razón para elegirte siempre a ti." }, { emoji: "👻", text: "No tienes forma de recordarle que merece mimarse esta semana — cuando no recibe señales, postpone la visita." }, { emoji: "💸", text: "Sin loyalty, compites solo por precio y ubicación. Con loyalty, eres el spa de SU vida." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: el programa de bienestar que tus clientes merecen", description: "Niveles VIP que reconocen a tus mejores clientes con beneficios exclusivos. Cada visita los acerca a más lujo.", benefitPoints: ["Niveles Jade → Cristal → Diamante con beneficios reales", "Puntos por cada tratamiento — acumulables sin límite", "Notificaciones de autocuidado personalizadas"] } },
		{ type: "how-it-works", order: 4, content: { headline: "Tu recepcionista registra en 5 segundos. El cliente se relaja.", subheadline: "Sin hardware extra. La recepcionista usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet al finalizar su tratamiento." }, { number: 2, icon: "📷", title: "La recepcionista escanea y registra", description: "Xtarly Cashier en iOS o Android. Ingresa el monto y confirma en 5 segundos." }, { number: 3, icon: "💎", title: "Puntos sumados. Nivel actualizado.", description: "Push al cliente. Su tarjeta Wallet refleja el nuevo nivel al instante." }] } },
		{ type: "wallet", order: 5, content: { headline: "Tu spa siempre presente como parte de su rutina de bienestar.", subheadline: "La tarjeta Diamante en su Apple Wallet es un símbolo de estatus.", benefits: ["Nivel VIP visible con cada apertura de Wallet", "Recordatorio cuando lleva tiempo sin su tratamiento", "Beneficios de nivel desbloqueados automáticamente", "Copa de vino, upgrade de tratamiento — directamente en su tarjeta"], stat: "Los miembros Diamante visitan 2.4x más frecuente y gastan 67% más por visita.", notificationText: "💆‍♀️ Han pasado 3 semanas desde tu último masaje — tu cuerpo lo necesita. Tienes 300 puntos listos." } },
		{ type: "journey", order: 6, content: { headline: "De cliente ocasional a miembro Diamante.", subheadline: "El viaje del bienestar con Xtarly.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Agrega la tarjeta Jade a Wallet al salir de su primer tratamiento." }, { number: 2, icon: "💆", title: "Acumula puntos", description: "$100 = 10 puntos. Cada tratamiento llena la barra más rápido." }, { number: 3, icon: "🥂", title: "Sube a Cristal", description: "Tratamiento de 30 min con upgrade + copa de vino incluida." }, { number: 4, icon: "💎", title: "Nivel Diamante", description: "Acceso a tratamientos exclusivos, sesión de nutrición gratis, fecha preferente." }, { number: 5, icon: "💛", title: "Tu spa es su ritual", description: "No solo viene para relajarse — viene porque es su spa de confianza." }] } },
		{ type: "analytics", order: 7, content: { headline: "Conoce el valor real de cada cliente.", subheadline: "LTV, frecuencia y riesgo de abandono — todo visible.", kpis: [{ label: "Clientes activos", value: "156", delta: "+12 este mes", positive: true }, { label: "Membership rate", value: "61%", delta: "+8% vs mes anterior", positive: true }, { label: "Ticket promedio", value: "$890", delta: "+$210 nivel Cristal+", positive: true }, { label: "Retención trimestral", value: "78%", delta: "+24% vs sin programa", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "Recuérdale que merece cuidarse.", subheadline: "El momento perfecto, el mensaje perfecto.", notifications: [{ type: "winback", title: "Xtarly Rewards", body: "💆‍♀️ Han pasado 3 semanas — tu cuerpo merece un descanso. Esta semana: 20% en masaje relajante.", time: "lun 10am" }, { type: "birthday", title: "Xtarly Rewards", body: "🌸 Hoy es tu día — tienes un tratamiento express gratis esperándote. ¡Feliz cumpleaños!", time: "8:00 AM" }, { type: "campaign", title: "Xtarly Rewards", body: "Semana del Bienestar 💎 — lunes a jueves, puntos x3 en cualquier tratamiento.", time: "dom 7pm" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Tu nivel Cristal vence en 15 días — 1 visita más para renovarlo.", time: "ayer" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "Un cliente que regresa más frecuente es rentabilidad pura.", subheadline: "Ejemplo real para un spa de 25 citas al día:", dailyVisits: 25, avgTicket: 850, enrollmentRate: 55, frequencyLift: 25, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "💎", title: "Niveles Jade → Cristal → Diamante", description: "Cada nivel desbloquea beneficios reales: upgrades, vino, acceso preferente." }, { emoji: "💳", title: "Apple & Google Wallet", description: "La tarjeta Diamante en su teléfono es un símbolo de pertenencia." }, { emoji: "📊", title: "LTV y retención por cliente", description: "Identifica quién está en riesgo de abandono antes de que pase." }, { emoji: "🔔", title: "Recordatorios de autocuidado", description: "\"Han pasado 3 semanas\" automático. Tu cliente vuelve antes." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Mis clientes de nivel Diamante gastan el doble que los que no tienen programa. Y lo mejor es que ya no tengo que recordarles venir — Xtarly les manda el push en el momento exacto.", author: "Valeria Torres", business: "Spa Serenita, Lomas de Chapultepec CDMX" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "Tus mejores clientes merecen el mejor programa.", subtitle: "Loyalty VIP listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function gyms(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Cada rep cuenta. Cada visita suma.", subheadline: "Convierte el abandono de enero en hábito de todo el año.", tagline: "Xtarly Rewards — Gyms & Fitness" } },
		{ type: "problem", order: 2, content: { title: "El problema real de los gyms", points: [{ emoji: "📉", text: "El 67% de los miembros que se inscriben en enero dejan de ir en marzo. La membresía activa no significa asistencia activa." }, { emoji: "💸", text: "Un miembro que cancela = $400-$1,800/mes perdidos. Retenerlo cuesta 5x menos que conseguir uno nuevo." }, { emoji: "👻", text: "Sin datos de asistencia, no sabes quién está a punto de cancelar hasta que ya canceló." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: el programa que convierte asistencia en hábito", description: "Puntos por cada visita registrada al gym. Retos mensuales, niveles por asistencia y notificaciones cuando llevan días sin venir.", benefitPoints: ["Puntos por asistencia + compras en tienda del gym", "Niveles por racha — Beginner → Warrior → Champion", "Push de reactivación cuando llevan 5+ días sin venir"] } },
		{ type: "how-it-works", order: 4, content: { headline: "La recepción registra en 5 segundos. El miembro entrena.", subheadline: "Sin hardware extra. La recepción usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El miembro muestra su QR", description: "Abre su app o Wallet al llegar. La recepción lo escanea." }, { number: 2, icon: "📷", title: "La recepción escanea y registra", description: "Xtarly Cashier en iOS o Android. Confirma la visita en 5 segundos." }, { number: 3, icon: "⭐", title: "Puntos sumados. Racha activa.", description: "Push al miembro. Su racha de asistencia visible en Wallet." }] } },
		{ type: "wallet", order: 5, content: { headline: "Su racha de asistencia visible en su teléfono.", subheadline: "La motivación de no romper la racha es más poderosa que cualquier anuncio.", benefits: ["Racha de días consecutivos visible en Wallet", "Notificación cuando llevan 3+ días sin venir: \"No rompas tu racha\"", "Nivel actualizado automáticamente al alcanzar la meta mensual", "Reto del mes — 20 visitas = mes gratis"], stat: "Los miembros con programa de puntos tienen 43% menos cancelaciones en los primeros 3 meses.", notificationText: "💪 Llevas 3 días sin venir — ¡no rompas tu racha de 14 días! Tu nivel Warrior te espera." } },
		{ type: "journey", order: 6, content: { headline: "De miembro que va \"cuando puede\" a miembro que no falta.", subheadline: "La gamificación que convierte el gym en hábito.", moments: [{ number: 1, icon: "📲", title: "Se inscribe", description: "Al pagar su primera membresía, agrega la tarjeta a Wallet." }, { number: 2, icon: "🏋️", title: "Acumula puntos", description: "Cada visita registrada suma puntos. Ve su racha crecer." }, { number: 3, icon: "🔥", title: "Reto del mes", description: "\"20 visitas en enero = mes de febrero gratis.\" No quiere perderlo." }, { number: 4, icon: "🏆", title: "Alcanza nivel Champion", description: "Clase de nutrición gratis, camiseta del gym, acceso a horarios premium." }, { number: 5, icon: "💛", title: "El gym es su identidad", description: "No va al gym — va A SU gym. La pertenencia evita la cancelación." }] } },
		{ type: "analytics", order: 7, content: { headline: "Sabe quién está a punto de cancelar antes de que cancele.", subheadline: "Asistencia, retención y riesgo de abandono en tiempo real.", kpis: [{ label: "Miembros activos", value: "423", delta: "+31 este mes", positive: true }, { label: "Tasa de cancelación", value: "4.2%", delta: "-2.8% vs sin programa", positive: true }, { label: "Asistencias/miembro/mes", value: "11.4", delta: "+3.8 con loyalty", positive: true }, { label: "Retención 3 meses", value: "74%", delta: "+21% vs sin programa", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "El push que hace que vuelvan antes de cancelar.", subheadline: "Reactivación automática cuando más importa.", notifications: [{ type: "winback", title: "Xtarly Rewards", body: "💪 Llevas 5 días sin venir — tu racha de 18 días está en riesgo. ¿Hoy a las 7pm?", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "🏆 Reto de enero: 20 visitas = mes gratis. Ya llevas 12, ¡te faltan 8!", time: "ene 15" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Tu nivel Warrior vence en 7 días — 2 visitas más para renovarlo.", time: "ayer" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Feliz cumpleaños! Esta semana tus clases grupales van por cuenta del gym.", time: "8:00 AM" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "Reducir cancelaciones es más rentable que conseguir miembros nuevos.", subheadline: "Ejemplo real para un gym de 350 miembros activos:", dailyVisits: 80, avgTicket: 650, enrollmentRate: 60, frequencyLift: 20, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "🏋️", title: "Puntos por asistencia", description: "Registro de visita + puntos automáticos. Sin torniquetes especiales." }, { emoji: "💳", title: "Niveles en Apple & Google Wallet", description: "Beginner → Warrior → Champion. La racha visible motiva la visita." }, { emoji: "📊", title: "Predicción de cancelaciones", description: "Identifica miembros con baja asistencia antes de que cancelen." }, { emoji: "🔔", title: "Push de reactivación", description: "\"No rompas tu racha\" automático a los 3 días sin venir." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Antes perdía 15 miembros por mes en febrero. Este año con los retos de asistencia y los puntos, solo perdí 4. El push de 'no rompas tu racha' es lo que más impacto tuvo — los que lo reciben, vienen.", author: "Carlos Acosta", business: "FitBox Gym, San Ángel CDMX" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "Menos cancelaciones. Más asistencia. Mismo esfuerzo.", subtitle: "Programa de loyalty para gym listo en 5 minutos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function salonesBelleza(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Tu belleza tiene nombre. Y ahora, recompensas.", subheadline: "El programa que ata al cliente al salón, no a la estilista.", tagline: "Xtarly Rewards — Salones de Belleza" } },
		{ type: "problem", order: 2, content: { title: "El problema real de los salones de belleza", points: [{ emoji: "💇‍♀️", text: "Cuando se va una estilista, se lleva a sus clientes. Sin loyalty, el cliente es de la persona, no del negocio." }, { emoji: "📅", text: "Los clientes posponen visitas sin un incentivo. \"El mes que viene\" se convierte en 3 meses sin volver." }, { emoji: "👻", text: "No tienes datos de cuándo fue la última visita de cada cliente ni cómo contactarlos para invitarlos." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: fideliza al cliente con el salón, no con la persona", description: "Sellos por servicio y puntos por monto. El cliente acumula beneficios en el salón — no con una estilista específica.", benefitPoints: ["Sellos por servicio — 10 servicios = 1 gratis", "Historial de servicios visible en su Wallet", "Recordatorio automático cuando es hora de retocar"] } },
		{ type: "how-it-works", order: 4, content: { headline: "La recepcionista registra en 5 segundos. La estilista hace su magia.", subheadline: "Sin hardware extra. La recepcionista usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "La clienta muestra su QR", description: "Abre su app o Wallet al pagar. La recepcionista lo escanea." }, { number: 2, icon: "📷", title: "La recepcionista escanea y registra", description: "Xtarly Cashier en iOS o Android. Confirma sello o puntos en 5 segundos." }, { number: 3, icon: "⭐", title: "Sello sumado. Historial actualizado.", description: "Push a la clienta. Wallet muestra progreso y fecha de visita." }] } },
		{ type: "wallet", order: 5, content: { headline: "Su historial de belleza siempre a la mano.", subheadline: "La tarjeta de tu salón como símbolo de confianza.", benefits: ["Historial de servicios visible — \"Última visita: 15 marzo\"", "Recordatorio automático cuando lleva 6 semanas sin venir", "Nivel Rose Gold → Diamond visible en su Wallet", "Notificación en cumpleaños con regalo de manicure"], stat: "Los salones con loyalty tienen 35% menos rotación de clientes cuando cambia personal.", notificationText: "💅 Han pasado 6 semanas — es hora de retocar tu tinte. Tienes 8 sellos acumulados 🌟" } },
		{ type: "journey", order: 6, content: { headline: "De clienta ocasional a clienta fiel al salón.", subheadline: "5 momentos de una relación que dura.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Agrega la tarjeta al Wallet al pagar su primer servicio." }, { number: 2, icon: "💇", title: "Acumula sellos", description: "Corte = 1 sello. Tinte = 2 sellos. Tratamiento = 1 sello." }, { number: 3, icon: "🔔", title: "Recordatorio de retoque", description: "\"Han pasado 6 semanas — tus raíces te llaman. ¿Agendamos?\"" }, { number: 4, icon: "💅", title: "Servicio gratis", description: "10 sellos = servicio básico gratis. Manicure de cumpleaños para Diamond." }, { number: 5, icon: "💛", title: "Es su salón de confianza", description: "No busca opciones. Vuelve al salón que la conoce y la recompensa." }] } },
		{ type: "analytics", order: 7, content: { headline: "Sabe cuándo fue la última visita de cada clienta.", subheadline: "Y cuál lleva demasiado tiempo sin volver.", kpis: [{ label: "Clientas activas", value: "289", delta: "+19 este mes", positive: true }, { label: "Membership rate", value: "52%", delta: "+6% vs mes anterior", positive: true }, { label: "Intervalo promedio", value: "4.2 sem", delta: "-1.1 sem con loyalty", positive: true }, { label: "Ticket promedio", value: "$420", delta: "+$85 nivel Rose Gold+", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "El recordatorio que la trae de vuelta antes de que vaya a otro salón.", subheadline: "Automático, personalizado, en el momento exacto.", notifications: [{ type: "winback", title: "Xtarly Rewards", body: "💇‍♀️ Han pasado 6 semanas — tus raíces merecen atención. Esta semana: 20% en tinte.", time: "lun 10am" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Feliz cumpleaños! Tu manicure de cumpleaños va por nuestra cuenta este mes.", time: "8:00 AM" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Tus sellos vencen en 7 días — ¡ya tienes 9, el servicio gratis está a 1 sello!", time: "vie 3pm" }, { type: "campaign", title: "Xtarly Rewards", body: "🌸 Viernes de spa capilar — tratamiento gratis con cualquier tinte. Solo Diamond.", time: "jue 6pm" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "Cada semana de retraso en la visita son ingresos que no llegan.", subheadline: "Ejemplo real para un salón de 40 servicios al día:", dailyVisits: 40, avgTicket: 400, enrollmentRate: 50, frequencyLift: 25, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "💇", title: "Sellos por servicio", description: "Corte, tinte, tratamiento — cada uno suma hacia el servicio gratis." }, { emoji: "💳", title: "Historial en Apple & Google Wallet", description: "\"Última visita\" visible en su teléfono — ella sabe cuándo volver." }, { emoji: "📊", title: "Seguimiento por clienta", description: "Cuándo fue, qué se hizo, cuánto gastó, cuándo es probable que vuelva." }, { emoji: "🔔", title: "Recordatorio de retoque automático", description: "6 semanas = push automático. No más clientas perdidas por olvido." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Perdí a mi mejor estilista y me llevó a 40 clientas. Con Xtarly, las que tenían sellos acumulados se quedaron porque no querían perder su progreso. Salvó el 70% de mis clientas.", author: "Lorena Vásquez", business: "Salón Studio L, Guadalajara JAL" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "El salón que fideliza nunca pierde a sus clientas.", subtitle: "Loyalty para salones listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function tiendasRopa(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Moda que te conoce. Recompensas que te quedan perfectas.", subheadline: "El club VIP que las grandes marcas tienen — ahora para tu tienda.", tagline: "Xtarly Rewards — Tiendas de Ropa" } },
		{ type: "problem", order: 2, content: { title: "El problema real de las tiendas de ropa", points: [{ emoji: "📦", text: "Shein, Zara y ASOS tienen apps con loyalty masivo. Tu tienda independiente compite sin ninguna ventaja de retención." }, { emoji: "💸", text: "El cliente visita en quincena y en temporadas. Sin programa, no hay razón para elegirte a ti entre todas las opciones." }, { emoji: "👻", text: "Tu cliente VIP — el que gasta $3,000-$10,000 al mes — no recibe ningún trato especial. Se siente igual que el que compra $200." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: el club exclusivo de tu tienda", description: "Puntos por cada compra y niveles VIP que dan a tus mejores clientes acceso anticipado a colecciones y beneficios que las grandes cadenas no pueden ofrecer.", benefitPoints: ["Puntos generosos — $1 = 2 puntos, 500 pts = $100 de descuento", "Early access a colecciones nuevas solo para Silver y Gold", "Eventos privados y personal shopper para nivel VIP Elite"] } },
		{ type: "how-it-works", order: 4, content: { headline: "La cajera registra en 5 segundos. El cliente acumula. Así de simple.", subheadline: "Sin hardware extra. La cajera usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet al pagar. La cajera lo escanea." }, { number: 2, icon: "📷", title: "La cajera escanea y registra", description: "Xtarly Cashier en iOS o Android. Ingresa el monto y confirma en 5 segundos." }, { number: 3, icon: "⭐", title: "Puntos sumados. Nivel actualizado.", description: "Push al cliente. Su nivel Silver, Gold o VIP Elite visible en Wallet." }] } },
		{ type: "wallet", order: 5, content: { headline: "La tarjeta que dice 'esta cliente es especial'.", subheadline: "Tus mejores clientes lo saben — y por eso vuelven.", benefits: ["Nivel VIP visible en su Wallet — identidad de marca", "Notificación de lanzamiento exclusiva 48h antes para Gold+", "Puntos y descuento disponible visible en todo momento", "Invitación a eventos privados directamente en su tarjeta"], stat: "Los clientes VIP Elite gastan en promedio 4.2x más al año que los clientes sin programa.", notificationText: "✨ Nueva colección primavera disponible para VIP Elite — preventa exclusiva hoy a las 12pm." } },
		{ type: "journey", order: 6, content: { headline: "De compradora ocasional a VIP Elite.", subheadline: "El viaje aspiracional de tu marca.", moments: [{ number: 1, icon: "📲", title: "Primera compra", description: "Agrega la tarjeta Silver a Wallet al pagar su primera compra." }, { number: 2, icon: "👗", title: "Acumula puntos", description: "Cada compra suma puntos. Puntos dobles en quincena y lanzamientos." }, { number: 3, icon: "🛍️", title: "Sube a Gold", description: "Early access 48h antes de la colección + envío gratis en compras online." }, { number: 4, icon: "👑", title: "Alcanza VIP Elite", description: "Personal shopper, evento privado, primera opción en piezas limitadas." }, { number: 5, icon: "💛", title: "Tu tienda es su tienda favorita", description: "El status social de ser VIP Elite es más valioso que el descuento." }] } },
		{ type: "analytics", order: 7, content: { headline: "Identifica a tus clientes más valiosos.", subheadline: "Y actívalos antes de que se vayan con la competencia.", kpis: [{ label: "Clientes activos", value: "347", delta: "+28 este mes", positive: true }, { label: "Membership rate", value: "39%", delta: "+5% vs mes anterior", positive: true }, { label: "Gasto anual VIP Elite", value: "$18,400", delta: "+4.2x vs sin programa", positive: true }, { label: "Tasa de recompra", value: "64%", delta: "+22% con loyalty", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "El mensaje que activa la compra impulsiva.", subheadline: "En el momento exacto, en el canal correcto.", notifications: [{ type: "campaign", title: "Xtarly Rewards", body: "✨ Nueva colección — preventa exclusiva 24h para Gold+. ¡Solo hoy y mañana!", time: "vie 10am" }, { type: "urgency", title: "Xtarly Rewards", body: "💰 Quincena llegó — puntos dobles en toda la tienda este 15 y 16.", time: "15 9am" }, { type: "winback", title: "Xtarly Rewards", body: "Han pasado 45 días 🛍️ — tienes $200 en puntos esperándote. ¿Algo nuevo llegó?", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "👗 Solo te faltan $800 para subir a Gold — descuentos anticipados y más te esperan.", time: "mar 11am" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "El trato VIP que genera el cliente que más gasta.", subheadline: "Ejemplo real para una boutique con 60 ventas al día:", dailyVisits: 60, avgTicket: 680, enrollmentRate: 35, frequencyLift: 30, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "👗", title: "Puntos por compra generosos", description: "$1 = 2 puntos. Puntos dobles en quincena y lanzamientos de temporada." }, { emoji: "💳", title: "Niveles VIP en Apple & Google Wallet", description: "Silver → Gold → VIP Elite. El estatus visible en su teléfono." }, { emoji: "📊", title: "Top clientes identificados", description: "Tus 50 mejores clientes por gasto anual. Tratalos diferente." }, { emoji: "🔔", title: "Preventa exclusiva automática", description: "Push para Gold+ 48h antes de lanzar colección al público." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Mis clientas VIP Elite gastan 4 veces más que las demás. Y lo mejor es que compran fuera de temporada — porque quieren mantener su nivel. El programa de loyalty convirtió mi boutique en un club.", author: "Andrea Soto", business: "Boutique Ánimo, Monterrey NL" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "Tu tienda puede tener el club VIP que tienen las grandes marcas.", subtitle: "Loyalty para boutique listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function farmacias(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Tu farmacia de confianza con recompensas que cuidan tu bolsillo.", subheadline: "La relación personal que las cadenas grandes nunca podrán ofrecer.", tagline: "Xtarly Rewards — Farmacias" } },
		{ type: "problem", order: 2, content: { title: "El problema real de las farmacias independientes", points: [{ emoji: "🏪", text: "Farmacias del Ahorro y Benavides tienen loyalty masivo con descuentos agresivos. Sin un programa, no puedes competir en precio." }, { emoji: "👻", text: "El cliente de medicamento crónico compra cada mes. Sin datos, no sabes si sigue viniendo o si se fue a la competencia." }, { emoji: "💊", text: "La farmacéutica independiente tiene algo que las cadenas no tienen: trato personalizado. El loyalty lo potencia." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: la farmacia que te conoce y te recompensa", description: "Puntos en cada compra, puntos extra en vitaminas y bienestar, y beneficios únicos para tus clientes más frecuentes.", benefitPoints: ["$1 gastado = 1 punto; 200 pts = $20 de descuento (10% efectivo)", "Puntos dobles en vitaminas, suplementos y productos de bienestar", "Consulta rápida gratis con acumulación de puntos (si tienes médico)"] } },
		{ type: "how-it-works", order: 4, content: { headline: "El farmacéutico registra en 5 segundos. Así de fácil.", subheadline: "Sin hardware extra. El farmacéutico usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El cliente muestra su QR", description: "Abre su app o Wallet al pagar. El farmacéutico lo escanea." }, { number: 2, icon: "📷", title: "El farmacéutico escanea y registra", description: "Xtarly Cashier en iOS o Android. Ingresa el monto y confirma en 5 segundos." }, { number: 3, icon: "⭐", title: "Puntos sumados al instante", description: "Push al cliente. Saldo de puntos y descuento disponible en Wallet." }] } },
		{ type: "wallet", order: 5, content: { headline: "El recordatorio de salud que ninguna cadena puede dar.", subheadline: "Porque tú conoces a tu cliente — y su salud importa.", benefits: ["Saldo de puntos visible en Wallet para próxima compra", "Recordatorio de surtido cuando se acerca la fecha de reposición", "Notificación de temporada — \"Vitamina C con puntos dobles esta semana\"", "Descuento disponible visible — motiva a no ir a otro lado"], stat: "Los pacientes con medicamento crónico que participan en loyalty tienen 78% de tasa de recompra mensual.", notificationText: "💊 Tu saldo de puntos: 180 puntos ($18 de descuento). Esta semana: vitamina C con puntos dobles." } },
		{ type: "journey", order: 6, content: { headline: "De paciente anónimo a cliente conocido y fiel.", subheadline: "El viaje de la confianza en salud.", moments: [{ number: 1, icon: "📲", title: "Primera compra", description: "Agrega la tarjeta a Wallet al surtir su primer medicamento." }, { number: 2, icon: "💊", title: "Acumula puntos", description: "Cada compra suma. Medicamentos, vitaminas, cuidado personal." }, { number: 3, icon: "🔔", title: "Recordatorio de surtido", description: "\"Tu medicamento se acaba en 5 días — pasa por él con tus puntos.\"" }, { number: 4, icon: "🎁", title: "Canjea su descuento", description: "200 puntos = $20 en su próxima compra. Siempre en tu farmacia." }, { number: 5, icon: "💛", title: "Tu farmacia es su farmacia", description: "Ya no busca opciones — va donde lo conocen y lo recompensan." }] } },
		{ type: "analytics", order: 7, content: { headline: "Identifica a tus clientes de medicamento crónico.", subheadline: "Y a los que llevan tiempo sin venir.", kpis: [{ label: "Clientes activos", value: "412", delta: "+34 este mes", positive: true }, { label: "Membership rate", value: "47%", delta: "+8% vs mes anterior", positive: true }, { label: "Compra promedio", value: "$320", delta: "+$67 con loyalty", positive: true }, { label: "Retención mensual", value: "82%", delta: "+19% vs sin programa", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "El recordatorio que mantiene la salud y tu farmacia llena.", subheadline: "Push automáticos en el momento que el cliente más los necesita.", notifications: [{ type: "winback", title: "Xtarly Rewards", body: "💊 Hace 35 días que no te vemos — ¿cómo está tu salud? Tienes $18 en puntos esperándote.", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "🤧 Temporada de gripe — vitamina C y zinc con puntos dobles esta semana.", time: "oct 1" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Tus puntos vencen en 7 días — ¡tienes $24 de descuento disponible!", time: "ayer" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Feliz cumpleaños! Tu vitamina del mes va con 50 puntos extra.", time: "8:00 AM" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "La farmacia que retiene al paciente crónico gana siempre.", subheadline: "Ejemplo real para una farmacia de 80 tickets al día:", dailyVisits: 80, avgTicket: 280, enrollmentRate: 45, frequencyLift: 20, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "💊", title: "Puntos por compra + salud", description: "Puntos dobles en vitaminas y suplementos — margen más alto para ti." }, { emoji: "💳", title: "Apple & Google Wallet", description: "Saldo de puntos siempre visible. El cliente sabe que tiene descuento." }, { emoji: "📊", title: "Pacientes crónicos identificados", description: "Sabe quién compra cada mes y cuándo debe volver." }, { emoji: "🔔", title: "Recordatorio de surtido", description: "Push automático cuando se acerca la fecha de reposición." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Mis clientes de medicamento crónico antes iban donde estuviera más cerca ese día. Ahora van a mi farmacia porque tienen puntos y porque les mando el recordatorio de surtido. Mi recompra mensual subió 23%.", author: "Dr. Eduardo Ríos", business: "Farmacia San Rafael, Querétaro QRO" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "La farmacia que cuida a sus clientes nunca los pierde.", subtitle: "Loyalty para farmacia listo en 5 minutos. Sin contratos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

function veterinarias(): Slides {
	return [
		{ type: "cover", order: 1, content: { headline: "Cuida a quien más quieres. Acumula recompensas en cada visita.", subheadline: "El único programa de lealtad con la foto de tu mascota en su Wallet.", tagline: "Xtarly Rewards — Clínicas Veterinarias" } },
		{ type: "problem", order: 2, content: { title: "El problema real de las veterinarias", points: [{ emoji: "🐾", text: "El dueño visita 2-8 veces al año. Sin recordatorios ni incentivos, postpone visitas de salud preventiva hasta que hay una urgencia." }, { emoji: "👻", text: "No tienes datos del historial de mascotas. Cuando el cliente se va, no puedes ni recordarles las vacunas anuales." }, { emoji: "💸", text: "Una mascota bien cuidada genera $8,000-$25,000 al año en servicios. Perder ese cliente es perder años de ingresos recurrentes." }] } },
		{ type: "solution", order: 3, content: { title: "Xtarly Rewards: el programa que cuida a mascotas y fideliza dueños", description: "Sellos por consulta, puntos por servicios y una tarjeta de Wallet única: con el nombre y foto de la mascota del cliente.", benefitPoints: ["5 consultas = 1 consulta básica gratis", "Recordatorio automático de vacunas y citas preventivas", "Tarjeta de Wallet personalizada con el nombre de la mascota"] } },
		{ type: "how-it-works", order: 4, content: { headline: "La recepción registra en 5 segundos. El veterinario atiende.", subheadline: "Sin hardware extra. La recepción usa Xtarly Cashier en su teléfono.", steps: [{ number: 1, icon: "📲", title: "El dueño muestra su QR", description: "Abre su app o Wallet al pagar. La recepción lo escanea." }, { number: 2, icon: "📷", title: "La recepción escanea y registra", description: "Xtarly Cashier en iOS o Android. Confirma sello o puntos en 5 segundos." }, { number: 3, icon: "🐾", title: "Sello de Rocky sumado al instante", description: "Push al dueño. La tarjeta de Rocky en Wallet se actualiza." }] } },
		{ type: "wallet", order: 5, content: { headline: "\"La tarjeta de Rocky\" siempre en el teléfono.", subheadline: "La conexión emocional más poderosa del loyalty: la mascota por nombre.", benefits: ["Tarjeta personalizada con el nombre de la mascota", "Recordatorio de vacunas anuales con el nombre del perro/gato", "Historial de visitas visible — vacunas, desparasitaciones, cirugías", "Notificación de cumpleaños de la mascota con regalo"], stat: "Los dueños con tarjeta de Wallet personalizada tienen 55% más visitas preventivas.", notificationText: "🐾 Rocky cumple 1 año en 2 semanas — ¡es hora de sus vacunas anuales! Agenda ahora y usa tus sellos." } },
		{ type: "journey", order: 6, content: { headline: "De dueño ansioso a dueño tranquilo con todo en orden.", subheadline: "El viaje de la salud preventiva de su mascota.", moments: [{ number: 1, icon: "📲", title: "Primera visita", description: "Crea el perfil de su mascota y agrega la tarjeta a Wallet." }, { number: 2, icon: "🐾", title: "Acumula sellos", description: "Cada consulta suma 1 sello. 5 sellos = consulta básica gratis." }, { number: 3, icon: "🔔", title: "Recordatorios de salud", description: "\"Rocky tiene vacunas pendientes esta semana — ¿agendamos?\"" }, { number: 4, icon: "🎁", title: "Canjea consulta gratis", description: "5 sellos = consulta básica sin costo. Microchip gratis al inscribirse." }, { number: 5, icon: "💛", title: "Su veterinaria de confianza", description: "Ya no busca opciones — Rocky solo va a donde lo conocen." }] } },
		{ type: "analytics", order: 7, content: { headline: "Sabe qué mascotas tienen vacunas pendientes esta semana.", subheadline: "Y cuáles no han venido en 4 meses.", kpis: [{ label: "Mascotas activas", value: "312", delta: "+24 este mes", positive: true }, { label: "Membership rate", value: "58%", delta: "+9% vs mes anterior", positive: true }, { label: "Visitas preventivas", value: "+47%", delta: "vs dueños sin programa", positive: true }, { label: "Gasto anual promedio", value: "$4,200", delta: "+$980 con loyalty", positive: true }] } },
		{ type: "notifications", order: 8, content: { headline: "El recordatorio que salva la salud de la mascota.", subheadline: "Automáticos y personalizados por nombre de mascota.", notifications: [{ type: "winback", title: "Xtarly Rewards", body: "🐾 Rocky tiene 4 meses sin revisión — ¿cómo está? Tiene una consulta de bienestar esperándolo.", time: "ayer" }, { type: "campaign", title: "Xtarly Rewards", body: "🌸 Semana de vacunación antirrábica — puntos x2 en vacunas. Rocky y sus amigos, bienvenidos.", time: "abr 1" }, { type: "birthday", title: "Xtarly Rewards", body: "🎂 ¡Rocky cumple 2 años! Su regalo de cumpleaños: 50 puntos extra en su próxima visita.", time: "8:00 AM" }, { type: "urgency", title: "Xtarly Rewards", body: "⏰ Las vacunas anuales de Rocky vencen en 2 semanas — agenda antes de que expire.", time: "ayer" }], stat: "CTR de push en loyalty: 8.1% — 8× más que email. Incluido en todos los planes." } },
		{ type: "roi", order: 9, content: { headline: "El dueño que previene gasta más — y es más fiel.", subheadline: "Ejemplo real para una veterinaria de 30 consultas al día:", dailyVisits: 30, avgTicket: 650, enrollmentRate: 55, frequencyLift: 30, planCost: 499 } },
		{ type: "vs-comparison", order: 10, content: VS_PAPER },
		{ type: "features", order: 11, content: { title: "Todo lo que incluye Xtarly Rewards", features: [{ emoji: "🐾", title: "Wallet con nombre de mascota", description: "\"Tarjeta de Rocky\" — la conexión emocional que ningún otro loyalty tiene." }, { emoji: "💳", title: "Sellos por consulta", description: "5 consultas = 1 gratis. El dueño siempre tiene razón para volver." }, { emoji: "📊", title: "Historial de salud por mascota", description: "Vacunas, cirugías, desparasitaciones. Todo registrado y visible." }, { emoji: "🔔", title: "Recordatorios de vacunas", description: "\"Las vacunas de Rocky vencen esta semana\" — automático y personalizado." }] } },
		{ type: "testimonial", order: 12, content: { quote: "Lo que más sorprendió a mis clientes fue la tarjeta con el nombre de su perro. Muestran la 'Tarjeta de Max' a todo el mundo. Mis citas de medicina preventiva subieron 40% — los dueños llegan ANTES de que haya urgencia.", author: "Dra. Carmen López", business: "Veterinaria San Francisco, Zapopan JAL" } },
		{ type: "pricing", order: 13, content: { title: "Empieza gratis. Crece sin límites.", plans: PLANS } },
		{ type: "cta", order: 14, content: { title: "La veterinaria que conoce a Rocky nunca lo pierde.", subtitle: "Loyalty veterinario con perfil de mascota listo en 5 minutos.", ctaText: "Empezar gratis", ctaUrl: "https://xtarly.com", contact: CTA_CONTACT } },
	];
}

// ─── MAP NICHO → FUNCIÓN ─────────────────────────────────────────────────────

const NICHE_SLIDES: Record<string, () => Slides> = {
	"Cafeterías": cafeterias,
	"Restaurantes": restaurantes,
	"Pastelerías": pastelerias,
	"Autolavados": autolavados,
	"Spas y Bienestar": spas,
	"Gyms y Fitness": gyms,
	"Salones de Belleza": salonesBelleza,
	"Tiendas de Ropa": tiendasRopa,
	"Farmacias y Salud": farmacias,
	"Clínicas Veterinarias": veterinarias,
};

// ─── SEED ─────────────────────────────────────────────────────────────────────

async function main() {
	console.log("🌱 Seeding presentations...\n");

	for (const [nicheName, slidesFn] of Object.entries(NICHE_SLIDES)) {
		const niche = await prisma.pitchNiche.findFirst({ where: { name: nicheName } });
		if (!niche) {
			console.warn(`⚠️  Nicho no encontrado: ${nicheName} — corre seed-niches primero.`);
			continue;
		}

		// Eliminar pitches anteriores para este nicho
		await prisma.pitch.deleteMany({ where: { nicheId: niche.id } });

		const pitch = await prisma.pitch.create({
			data: {
				title: `Xtarly Rewards — ${nicheName}`,
				nicheId: niche.id,
				isPublished: true,
				slides: {
					create: slidesFn().map((s) => ({
						order: s.order,
						type: s.type,
						content: s.content,
					})),
				},
			},
		});

		console.log(`✅ ${nicheName}: ${pitch.id} (14 slides)`);
	}

	console.log("\n✨ Done.");
	await prisma.$disconnect();
}

main().catch((e) => {
	console.error(e);
	prisma.$disconnect();
	process.exit(1);
});
